name: build-windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  windows-mingw:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja

      - name: Configure (CMake + Ninja)
        shell: msys2 {0}
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: msys2 {0}
        run: cmake --build build --config Release -j 2

      - name: Upload artifact (yuv-corruptor.exe)
        uses: actions/upload-artifact@v4
        with:
          name: yuv-corruptor-windows-x86_64
          path: build/yuv-corruptor.exe
          if-no-files-found: error


